export interface Element {
  number: number;
  symbol: string;
  name: string;
  atomic_mass: number;
  category: string;
  group: number;
  period: number;
  summary: string;
  electron_configuration: string;
  xpos: number;
  ypos: number;
  melt?: number;
  boil?: number;
  shells: number[];
  ionCharge?: string[];
  electronegativity?: number;
  atomicRadius?: number;
  ionizationEnergy?: number;
  discoveredBy?: string;
  yearDiscovered?: number | string;
  uses?: string[];
  funFact?: string;
}

export const elements: Element[] = [
  { number: 1, symbol: "H", name: "Hydrogen", atomic_mass: 1.008, category: "diatomic nonmetal", group: 1, period: 1, summary: "Hydrogen is a chemical element with symbol H and atomic number 1. With a standard atomic weight of 1.008, hydrogen is the lightest element on the periodic table.", electron_configuration: "1s1", xpos: 1, ypos: 1, melt: 13.99, boil: 20.271, shells: [1], ionCharge: ["+1", "-1"], electronegativity: 2.20, atomicRadius: 53, ionizationEnergy: 1312, discoveredBy: "Henry Cavendish", yearDiscovered: 1766, uses: ["Rocket fuel", "Fuel cells", "Ammonia production", "Hydrogenation"], funFact: "Hydrogen makes up about 75% of all normal matter in the universe by mass." },
  { number: 2, symbol: "He", name: "Helium", atomic_mass: 4.0026, category: "noble gas", group: 18, period: 1, summary: "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas.", electron_configuration: "1s2", xpos: 18, ypos: 1, melt: 0.95, boil: 4.222, shells: [2], ionCharge: ["0"], electronegativity: undefined, atomicRadius: 31, ionizationEnergy: 2372, discoveredBy: "Pierre Janssen", yearDiscovered: 1868, uses: ["Balloons", "Cryogenics", "MRI machines", "Deep-sea diving"], funFact: "Helium is the only element that cannot be solidified by cooling at normal pressure." },
  { number: 3, symbol: "Li", name: "Lithium", atomic_mass: 6.94, category: "alkali metal", group: 1, period: 2, summary: "Lithium is a chemical element with symbol Li and atomic number 3. It is a soft, silvery-white alkali metal.", electron_configuration: "[He] 2s1", xpos: 1, ypos: 2, melt: 453.65, boil: 1603, shells: [2, 1], ionCharge: ["+1"], electronegativity: 0.98, atomicRadius: 167, ionizationEnergy: 520, discoveredBy: "Johan August Arfwedson", yearDiscovered: 1817, uses: ["Batteries", "Mood stabilizers", "Ceramics", "Lubricants"], funFact: "Lithium is so light it can float on water!" },
  { number: 4, symbol: "Be", name: "Beryllium", atomic_mass: 9.0122, category: "alkaline earth metal", group: 2, period: 2, summary: "Beryllium is a chemical element with symbol Be and atomic number 4.", electron_configuration: "[He] 2s2", xpos: 2, ypos: 2, melt: 1560, boil: 2742, shells: [2, 2], ionCharge: ["+2"], electronegativity: 1.57, atomicRadius: 112, ionizationEnergy: 900, discoveredBy: "Louis Nicolas Vauquelin", yearDiscovered: 1798, uses: ["Aerospace materials", "X-ray windows", "Nuclear reactors"], funFact: "Beryllium is transparent to X-rays and is used in X-ray tube windows." },
  { number: 5, symbol: "B", name: "Boron", atomic_mass: 10.81, category: "metalloid", group: 13, period: 2, summary: "Boron is a chemical element with symbol B and atomic number 5.", electron_configuration: "[He] 2s2 2p1", xpos: 13, ypos: 2, melt: 2349, boil: 4200, shells: [2, 3], ionCharge: ["+3"], electronegativity: 2.04, atomicRadius: 87, ionizationEnergy: 801, discoveredBy: "Joseph Louis Gay-Lussac", yearDiscovered: 1808, uses: ["Fiberglass", "Detergents", "Semiconductors"], funFact: "Boron is essential for plant growth but toxic to plants in large quantities." },
  { number: 6, symbol: "C", name: "Carbon", atomic_mass: 12.011, category: "polyatomic nonmetal", group: 14, period: 2, summary: "Carbon is a chemical element with symbol C and atomic number 6. It is nonmetallic and tetravalent.", electron_configuration: "[He] 2s2 2p2", xpos: 14, ypos: 2, melt: 3800, boil: 4300, shells: [2, 4], ionCharge: ["+4", "-4"], electronegativity: 2.55, atomicRadius: 67, ionizationEnergy: 1087, discoveredBy: "Ancient", yearDiscovered: "Ancient", uses: ["Steel production", "Fuel", "Plastics", "Diamonds"], funFact: "Carbon can form nearly 10 million different compounds, more than any other element." },
  { number: 7, symbol: "N", name: "Nitrogen", atomic_mass: 14.007, category: "diatomic nonmetal", group: 15, period: 2, summary: "Nitrogen is a chemical element with symbol N and atomic number 7.", electron_configuration: "[He] 2s2 2p3", xpos: 15, ypos: 2, melt: 63.15, boil: 77.355, shells: [2, 5], ionCharge: ["+5", "+3", "-3"], electronegativity: 3.04, atomicRadius: 56, ionizationEnergy: 1402, discoveredBy: "Daniel Rutherford", yearDiscovered: 1772, uses: ["Fertilizers", "Explosives", "Food preservation", "Cryogenics"], funFact: "Nitrogen makes up about 78% of Earth's atmosphere." },
  { number: 8, symbol: "O", name: "Oxygen", atomic_mass: 15.999, category: "diatomic nonmetal", group: 16, period: 2, summary: "Oxygen is a chemical element with symbol O and atomic number 8.", electron_configuration: "[He] 2s2 2p4", xpos: 16, ypos: 2, melt: 54.36, boil: 90.188, shells: [2, 6], ionCharge: ["-2"], electronegativity: 3.44, atomicRadius: 48, ionizationEnergy: 1314, discoveredBy: "Joseph Priestley", yearDiscovered: 1774, uses: ["Respiration", "Combustion", "Steel production", "Medical use"], funFact: "Oxygen is the most abundant element in Earth's crust at about 46%." },
  { number: 9, symbol: "F", name: "Fluorine", atomic_mass: 18.998, category: "diatomic nonmetal", group: 17, period: 2, summary: "Fluorine is a chemical element with symbol F and atomic number 9.", electron_configuration: "[He] 2s2 2p5", xpos: 17, ypos: 2, melt: 53.48, boil: 85.03, shells: [2, 7], ionCharge: ["-1"], electronegativity: 3.98, atomicRadius: 42, ionizationEnergy: 1681, discoveredBy: "André-Marie Ampère", yearDiscovered: 1886, uses: ["Toothpaste", "Teflon", "Refrigerants", "Uranium enrichment"], funFact: "Fluorine is the most reactive and electronegative of all elements." },
  { number: 10, symbol: "Ne", name: "Neon", atomic_mass: 20.180, category: "noble gas", group: 18, period: 2, summary: "Neon is a chemical element with symbol Ne and atomic number 10. It is a noble gas.", electron_configuration: "[He] 2s2 2p6", xpos: 18, ypos: 2, melt: 24.56, boil: 27.104, shells: [2, 8], ionCharge: ["0"], electronegativity: undefined, atomicRadius: 38, ionizationEnergy: 2081, discoveredBy: "William Ramsay", yearDiscovered: 1898, uses: ["Neon signs", "Lasers", "Cryogenic refrigerant"], funFact: "Neon glows reddish-orange in vacuum discharge tubes, giving 'neon signs' their name." },
  { number: 11, symbol: "Na", name: "Sodium", atomic_mass: 22.990, category: "alkali metal", group: 1, period: 3, summary: "Sodium is a chemical element with symbol Na and atomic number 11.", electron_configuration: "[Ne] 3s1", xpos: 1, ypos: 3, melt: 370.94, boil: 1156.09, shells: [2, 8, 1], ionCharge: ["+1"], electronegativity: 0.93, atomicRadius: 190, ionizationEnergy: 496, discoveredBy: "Humphry Davy", yearDiscovered: 1807, uses: ["Table salt", "Street lights", "Chemical synthesis"], funFact: "Sodium reacts so violently with water that it can catch fire!" },
  { number: 12, symbol: "Mg", name: "Magnesium", atomic_mass: 24.305, category: "alkaline earth metal", group: 2, period: 3, summary: "Magnesium is a chemical element with symbol Mg and atomic number 12.", electron_configuration: "[Ne] 3s2", xpos: 2, ypos: 3, melt: 923, boil: 1363, shells: [2, 8, 2], ionCharge: ["+2"], electronegativity: 1.31, atomicRadius: 145, ionizationEnergy: 738, discoveredBy: "Joseph Black", yearDiscovered: 1755, uses: ["Alloys", "Fireworks", "Medicine", "Photography"], funFact: "Magnesium burns with a brilliant white light, used in old camera flash bulbs." },
  { number: 13, symbol: "Al", name: "Aluminium", atomic_mass: 26.982, category: "post-transition metal", group: 13, period: 3, summary: "Aluminium is a chemical element with symbol Al and atomic number 13.", electron_configuration: "[Ne] 3s2 3p1", xpos: 13, ypos: 3, melt: 933.47, boil: 2743, shells: [2, 8, 3], ionCharge: ["+3"], electronegativity: 1.61, atomicRadius: 118, ionizationEnergy: 578, discoveredBy: "Hans Christian Ørsted", yearDiscovered: 1825, uses: ["Aircraft", "Packaging", "Construction", "Electrical wires"], funFact: "Aluminium was once more valuable than gold before cheap extraction methods were developed." },
  { number: 14, symbol: "Si", name: "Silicon", atomic_mass: 28.085, category: "metalloid", group: 14, period: 3, summary: "Silicon is a chemical element with symbol Si and atomic number 14.", electron_configuration: "[Ne] 3s2 3p2", xpos: 14, ypos: 3, melt: 1687, boil: 3538, shells: [2, 8, 4], ionCharge: ["+4", "-4"], electronegativity: 1.90, atomicRadius: 111, ionizationEnergy: 786, discoveredBy: "Jöns Jacob Berzelius", yearDiscovered: 1824, uses: ["Computer chips", "Solar cells", "Glass", "Silicones"], funFact: "Silicon Valley is named after silicon, the key material in computer chips." },
  { number: 15, symbol: "P", name: "Phosphorus", atomic_mass: 30.974, category: "polyatomic nonmetal", group: 15, period: 3, summary: "Phosphorus is a chemical element with symbol P and atomic number 15.", electron_configuration: "[Ne] 3s2 3p3", xpos: 15, ypos: 3, melt: 317.3, boil: 550, shells: [2, 8, 5], ionCharge: ["+5", "+3", "-3"], electronegativity: 2.19, atomicRadius: 98, ionizationEnergy: 1012, discoveredBy: "Hennig Brand", yearDiscovered: 1669, uses: ["Fertilizers", "Matches", "Detergents", "Steel production"], funFact: "White phosphorus glows in the dark due to chemiluminescence!" },
  { number: 16, symbol: "S", name: "Sulfur", atomic_mass: 32.06, category: "polyatomic nonmetal", group: 16, period: 3, summary: "Sulfur is a chemical element with symbol S and atomic number 16.", electron_configuration: "[Ne] 3s2 3p4", xpos: 16, ypos: 3, melt: 388.36, boil: 717.8, shells: [2, 8, 6], ionCharge: ["+6", "+4", "-2"], electronegativity: 2.58, atomicRadius: 88, ionizationEnergy: 1000, discoveredBy: "Ancient", yearDiscovered: "Ancient", uses: ["Sulfuric acid", "Rubber vulcanization", "Fungicides", "Gunpowder"], funFact: "Sulfur was known to ancient people as 'brimstone' and associated with the underworld." },
  { number: 17, symbol: "Cl", name: "Chlorine", atomic_mass: 35.45, category: "diatomic nonmetal", group: 17, period: 3, summary: "Chlorine is a chemical element with symbol Cl and atomic number 17.", electron_configuration: "[Ne] 3s2 3p5", xpos: 17, ypos: 3, melt: 171.6, boil: 239.11, shells: [2, 8, 7], ionCharge: ["-1", "+1", "+5", "+7"], electronegativity: 3.16, atomicRadius: 79, ionizationEnergy: 1251, discoveredBy: "Carl Wilhelm Scheele", yearDiscovered: 1774, uses: ["Water treatment", "PVC plastic", "Bleach", "Disinfectants"], funFact: "Chlorine is added to swimming pools and drinking water to kill harmful bacteria." },
  { number: 18, symbol: "Ar", name: "Argon", atomic_mass: 39.948, category: "noble gas", group: 18, period: 3, summary: "Argon is a chemical element with symbol Ar and atomic number 18.", electron_configuration: "[Ne] 3s2 3p6", xpos: 18, ypos: 3, melt: 83.81, boil: 87.302, shells: [2, 8, 8], ionCharge: ["0"], electronegativity: undefined, atomicRadius: 71, ionizationEnergy: 1521, discoveredBy: "Lord Rayleigh", yearDiscovered: 1894, uses: ["Light bulbs", "Welding", "Preserving documents"], funFact: "Argon makes up about 1% of Earth's atmosphere, making it the third most abundant gas." },
  { number: 19, symbol: "K", name: "Potassium", atomic_mass: 39.098, category: "alkali metal", group: 1, period: 4, summary: "Potassium is a chemical element with symbol K and atomic number 19.", electron_configuration: "[Ar] 4s1", xpos: 1, ypos: 4, melt: 336.7, boil: 1032, shells: [2, 8, 8, 1], ionCharge: ["+1"], electronegativity: 0.82, atomicRadius: 243, ionizationEnergy: 419, discoveredBy: "Humphry Davy", yearDiscovered: 1807, uses: ["Fertilizers", "Soap", "Glass making"], funFact: "Potassium is essential for human health and is found in bananas!" },
  { number: 20, symbol: "Ca", name: "Calcium", atomic_mass: 40.078, category: "alkaline earth metal", group: 2, period: 4, summary: "Calcium is a chemical element with symbol Ca and atomic number 20.", electron_configuration: "[Ar] 4s2", xpos: 2, ypos: 4, melt: 1115, boil: 1757, shells: [2, 8, 8, 2], ionCharge: ["+2"], electronegativity: 1.00, atomicRadius: 194, ionizationEnergy: 590, discoveredBy: "Humphry Davy", yearDiscovered: 1808, uses: ["Building materials", "Supplements", "Steel production"], funFact: "Your bones and teeth contain about 1 kg of calcium!" },
  { number: 21, symbol: "Sc", name: "Scandium", atomic_mass: 44.956, category: "transition metal", group: 3, period: 4, summary: "Scandium is a chemical element with symbol Sc and atomic number 21.", electron_configuration: "[Ar] 3d1 4s2", xpos: 3, ypos: 4, melt: 1814, boil: 3109, shells: [2, 8, 9, 2], ionCharge: ["+3"], electronegativity: 1.36, atomicRadius: 184, ionizationEnergy: 633, discoveredBy: "Lars Fredrik Nilson", yearDiscovered: 1879, uses: ["Aerospace alloys", "Sports equipment", "Lighting"], funFact: "Scandium is used in high-end bicycle frames and baseball bats." },
  { number: 22, symbol: "Ti", name: "Titanium", atomic_mass: 47.867, category: "transition metal", group: 4, period: 4, summary: "Titanium is a chemical element with symbol Ti and atomic number 22.", electron_configuration: "[Ar] 3d2 4s2", xpos: 4, ypos: 4, melt: 1941, boil: 3560, shells: [2, 8, 10, 2], ionCharge: ["+4", "+3", "+2"], electronegativity: 1.54, atomicRadius: 176, ionizationEnergy: 659, discoveredBy: "William Gregor", yearDiscovered: 1791, uses: ["Aircraft", "Medical implants", "Jewelry", "Paint"], funFact: "Titanium is as strong as steel but 45% lighter!" },
  { number: 23, symbol: "V", name: "Vanadium", atomic_mass: 50.942, category: "transition metal", group: 5, period: 4, summary: "Vanadium is a chemical element with symbol V and atomic number 23.", electron_configuration: "[Ar] 3d3 4s2", xpos: 5, ypos: 4, melt: 2183, boil: 3680, shells: [2, 8, 11, 2], ionCharge: ["+5", "+4", "+3", "+2"], electronegativity: 1.63, atomicRadius: 171, ionizationEnergy: 651, discoveredBy: "Andrés Manuel del Río", yearDiscovered: 1801, uses: ["Steel alloys", "Jet engines", "Batteries"], funFact: "Vanadium was named after Vanadis, the Scandinavian goddess of beauty." },
  { number: 24, symbol: "Cr", name: "Chromium", atomic_mass: 51.996, category: "transition metal", group: 6, period: 4, summary: "Chromium is a chemical element with symbol Cr and atomic number 24.", electron_configuration: "[Ar] 3d5 4s1", xpos: 6, ypos: 4, melt: 2180, boil: 2944, shells: [2, 8, 13, 1], ionCharge: ["+6", "+3", "+2"], electronegativity: 1.66, atomicRadius: 166, ionizationEnergy: 653, discoveredBy: "Louis Nicolas Vauquelin", yearDiscovered: 1797, uses: ["Chrome plating", "Stainless steel", "Pigments"], funFact: "Rubies get their red color from chromium impurities!" },
  { number: 25, symbol: "Mn", name: "Manganese", atomic_mass: 54.938, category: "transition metal", group: 7, period: 4, summary: "Manganese is a chemical element with symbol Mn and atomic number 25.", electron_configuration: "[Ar] 3d5 4s2", xpos: 7, ypos: 4, melt: 1519, boil: 2334, shells: [2, 8, 13, 2], ionCharge: ["+7", "+4", "+2"], electronegativity: 1.55, atomicRadius: 161, ionizationEnergy: 717, discoveredBy: "Carl Wilhelm Scheele", yearDiscovered: 1774, uses: ["Steel production", "Batteries", "Aluminum alloys"], funFact: "Manganese is essential for photosynthesis in plants." },
  { number: 26, symbol: "Fe", name: "Iron", atomic_mass: 55.845, category: "transition metal", group: 8, period: 4, summary: "Iron is a chemical element with symbol Fe and atomic number 26.", electron_configuration: "[Ar] 3d6 4s2", xpos: 8, ypos: 4, melt: 1811, boil: 3134, shells: [2, 8, 14, 2], ionCharge: ["+3", "+2"], electronegativity: 1.83, atomicRadius: 156, ionizationEnergy: 762, discoveredBy: "Ancient", yearDiscovered: "Ancient", uses: ["Steel", "Construction", "Tools", "Transportation"], funFact: "The core of Earth is mostly iron, and it creates our magnetic field!" },
  { number: 27, symbol: "Co", name: "Cobalt", atomic_mass: 58.933, category: "transition metal", group: 9, period: 4, summary: "Cobalt is a chemical element with symbol Co and atomic number 27.", electron_configuration: "[Ar] 3d7 4s2", xpos: 9, ypos: 4, melt: 1768, boil: 3200, shells: [2, 8, 15, 2], ionCharge: ["+3", "+2"], electronegativity: 1.88, atomicRadius: 152, ionizationEnergy: 760, discoveredBy: "Georg Brandt", yearDiscovered: 1735, uses: ["Batteries", "Superalloys", "Magnets", "Blue pigments"], funFact: "Cobalt gives a distinctive blue color to glass and ceramics." },
  { number: 28, symbol: "Ni", name: "Nickel", atomic_mass: 58.693, category: "transition metal", group: 10, period: 4, summary: "Nickel is a chemical element with symbol Ni and atomic number 28.", electron_configuration: "[Ar] 3d8 4s2", xpos: 10, ypos: 4, melt: 1728, boil: 3186, shells: [2, 8, 16, 2], ionCharge: ["+2", "+3"], electronegativity: 1.91, atomicRadius: 149, ionizationEnergy: 737, discoveredBy: "Axel Fredrik Cronstedt", yearDiscovered: 1751, uses: ["Coins", "Stainless steel", "Batteries", "Plating"], funFact: "The US 'nickel' coin actually contains more copper than nickel!" },
  { number: 29, symbol: "Cu", name: "Copper", atomic_mass: 63.546, category: "transition metal", group: 11, period: 4, summary: "Copper is a chemical element with symbol Cu and atomic number 29.", electron_configuration: "[Ar] 3d10 4s1", xpos: 11, ypos: 4, melt: 1357.77, boil: 2835, shells: [2, 8, 18, 1], ionCharge: ["+2", "+1"], electronegativity: 1.90, atomicRadius: 145, ionizationEnergy: 746, discoveredBy: "Ancient", yearDiscovered: "Ancient", uses: ["Electrical wires", "Plumbing", "Coins", "Alloys"], funFact: "Copper was the first metal to be smelted by humans around 5000 BCE!" },
  { number: 30, symbol: "Zn", name: "Zinc", atomic_mass: 65.38, category: "transition metal", group: 12, period: 4, summary: "Zinc is a chemical element with symbol Zn and atomic number 30.", electron_configuration: "[Ar] 3d10 4s2", xpos: 12, ypos: 4, melt: 692.68, boil: 1180, shells: [2, 8, 18, 2], ionCharge: ["+2"], electronegativity: 1.65, atomicRadius: 142, ionizationEnergy: 906, discoveredBy: "Ancient", yearDiscovered: "Ancient", uses: ["Galvanizing steel", "Batteries", "Alloys", "Supplements"], funFact: "Zinc is essential for human health and helps wounds heal faster." },
  { number: 31, symbol: "Ga", name: "Gallium", atomic_mass: 69.723, category: "post-transition metal", group: 13, period: 4, summary: "Gallium is a chemical element with symbol Ga and atomic number 31.", electron_configuration: "[Ar] 3d10 4s2 4p1", xpos: 13, ypos: 4, melt: 302.91, boil: 2673, shells: [2, 8, 18, 3], ionCharge: ["+3"], electronegativity: 1.81, atomicRadius: 136, ionizationEnergy: 579, discoveredBy: "Paul Emile Lecoq de Boisbaudran", yearDiscovered: 1875, uses: ["Semiconductors", "LEDs", "Solar panels"], funFact: "Gallium melts at just 29.76°C - you can melt it in your hand!" },
  { number: 32, symbol: "Ge", name: "Germanium", atomic_mass: 72.630, category: "metalloid", group: 14, period: 4, summary: "Germanium is a chemical element with symbol Ge and atomic number 32.", electron_configuration: "[Ar] 3d10 4s2 4p2", xpos: 14, ypos: 4, melt: 1211.4, boil: 3106, shells: [2, 8, 18, 4], ionCharge: ["+4", "+2"], electronegativity: 2.01, atomicRadius: 125, ionizationEnergy: 762, discoveredBy: "Clemens Winkler", yearDiscovered: 1886, uses: ["Fiber optics", "Infrared optics", "Transistors"], funFact: "Germanium was predicted by Mendeleev before it was discovered!" },
  { number: 33, symbol: "As", name: "Arsenic", atomic_mass: 74.922, category: "metalloid", group: 15, period: 4, summary: "Arsenic is a chemical element with symbol As and atomic number 33.", electron_configuration: "[Ar] 3d10 4s2 4p3", xpos: 15, ypos: 4, melt: 1090, boil: 887, shells: [2, 8, 18, 5], ionCharge: ["+5", "+3", "-3"], electronegativity: 2.18, atomicRadius: 114, ionizationEnergy: 947, discoveredBy: "Albertus Magnus", yearDiscovered: 1250, uses: ["Semiconductors", "Wood preservatives", "Pesticides"], funFact: "Arsenic was historically known as 'inheritance powder' due to its use as a poison." },
  { number: 34, symbol: "Se", name: "Selenium", atomic_mass: 78.971, category: "polyatomic nonmetal", group: 16, period: 4, summary: "Selenium is a chemical element with symbol Se and atomic number 34.", electron_configuration: "[Ar] 3d10 4s2 4p4", xpos: 16, ypos: 4, melt: 494, boil: 958, shells: [2, 8, 18, 6], ionCharge: ["+6", "+4", "-2"], electronegativity: 2.55, atomicRadius: 103, ionizationEnergy: 941, discoveredBy: "Jöns Jacob Berzelius", yearDiscovered: 1817, uses: ["Solar cells", "Photocopiers", "Glass making"], funFact: "Selenium is an essential trace element needed for human health." },
  { number: 35, symbol: "Br", name: "Bromine", atomic_mass: 79.904, category: "diatomic nonmetal", group: 17, period: 4, summary: "Bromine is a chemical element with symbol Br and atomic number 35.", electron_configuration: "[Ar] 3d10 4s2 4p5", xpos: 17, ypos: 4, melt: 265.8, boil: 332, shells: [2, 8, 18, 7], ionCharge: ["-1", "+1", "+5"], electronegativity: 2.96, atomicRadius: 94, ionizationEnergy: 1140, discoveredBy: "Antoine Jérôme Balard", yearDiscovered: 1826, uses: ["Flame retardants", "Photography", "Water purification"], funFact: "Bromine is one of only two elements that are liquid at room temperature!" },
  { number: 36, symbol: "Kr", name: "Krypton", atomic_mass: 83.798, category: "noble gas", group: 18, period: 4, summary: "Krypton is a chemical element with symbol Kr and atomic number 36.", electron_configuration: "[Ar] 3d10 4s2 4p6", xpos: 18, ypos: 4, melt: 115.78, boil: 119.93, shells: [2, 8, 18, 8], ionCharge: ["0"], electronegativity: 3.00, atomicRadius: 88, ionizationEnergy: 1351, discoveredBy: "William Ramsay", yearDiscovered: 1898, uses: ["Lighting", "Lasers", "Photography flashes"], funFact: "Despite its name, krypton has nothing to do with Superman's home planet!" },
  { number: 37, symbol: "Rb", name: "Rubidium", atomic_mass: 85.468, category: "alkali metal", group: 1, period: 5, summary: "Rubidium is a chemical element with symbol Rb and atomic number 37.", electron_configuration: "[Kr] 5s1", xpos: 1, ypos: 5, melt: 312.45, boil: 961, shells: [2, 8, 18, 8, 1], ionCharge: ["+1"], electronegativity: 0.82, atomicRadius: 265, ionizationEnergy: 403, discoveredBy: "Robert Bunsen", yearDiscovered: 1861, uses: ["Atomic clocks", "Fireworks", "Research"], funFact: "Rubidium is used in the world's most accurate atomic clocks." },
  { number: 38, symbol: "Sr", name: "Strontium", atomic_mass: 87.62, category: "alkaline earth metal", group: 2, period: 5, summary: "Strontium is a chemical element with symbol Sr and atomic number 38.", electron_configuration: "[Kr] 5s2", xpos: 2, ypos: 5, melt: 1050, boil: 1650, shells: [2, 8, 18, 8, 2], ionCharge: ["+2"], electronegativity: 0.95, atomicRadius: 219, ionizationEnergy: 550, discoveredBy: "William Cruickshank", yearDiscovered: 1790, uses: ["Fireworks (red color)", "Toothpaste", "Glow-in-dark paint"], funFact: "Strontium gives fireworks their brilliant red color!" },
  { number: 39, symbol: "Y", name: "Yttrium", atomic_mass: 88.906, category: "transition metal", group: 3, period: 5, summary: "Yttrium is a chemical element with symbol Y and atomic number 39.", electron_configuration: "[Kr] 4d1 5s2", xpos: 3, ypos: 5, melt: 1799, boil: 3609, shells: [2, 8, 18, 9, 2], ionCharge: ["+3"], electronegativity: 1.22, atomicRadius: 212, ionizationEnergy: 600, discoveredBy: "Johan Gadolin", yearDiscovered: 1794, uses: ["LEDs", "Superconductors", "Lasers", "TV screens"], funFact: "Yttrium is named after Ytterby, a Swedish village that gave its name to 4 elements!" },
  { number: 40, symbol: "Zr", name: "Zirconium", atomic_mass: 91.224, category: "transition metal", group: 4, period: 5, summary: "Zirconium is a chemical element with symbol Zr and atomic number 40.", electron_configuration: "[Kr] 4d2 5s2", xpos: 4, ypos: 5, melt: 2128, boil: 4682, shells: [2, 8, 18, 10, 2], ionCharge: ["+4"], electronegativity: 1.33, atomicRadius: 206, ionizationEnergy: 640, discoveredBy: "Martin Heinrich Klaproth", yearDiscovered: 1789, uses: ["Nuclear reactors", "Ceramics", "Jewelry"], funFact: "Cubic zirconia (ZrO₂) is used as a diamond substitute in jewelry." },
  { number: 41, symbol: "Nb", name: "Niobium", atomic_mass: 92.906, category: "transition metal", group: 5, period: 5, summary: "Niobium is a chemical element with symbol Nb and atomic number 41.", electron_configuration: "[Kr] 4d4 5s1", xpos: 5, ypos: 5, melt: 2750, boil: 5017, shells: [2, 8, 18, 12, 1], ionCharge: ["+5", "+3"], electronegativity: 1.60, atomicRadius: 198, ionizationEnergy: 652, discoveredBy: "Charles Hatchett", yearDiscovered: 1801, uses: ["Superconducting magnets", "Jet engines", "Jewelry"], funFact: "Brazil produces about 90% of the world's niobium!" },
  { number: 42, symbol: "Mo", name: "Molybdenum", atomic_mass: 95.95, category: "transition metal", group: 6, period: 5, summary: "Molybdenum is a chemical element with symbol Mo and atomic number 42.", electron_configuration: "[Kr] 4d5 5s1", xpos: 6, ypos: 5, melt: 2896, boil: 4912, shells: [2, 8, 18, 13, 1], ionCharge: ["+6", "+4", "+2"], electronegativity: 2.16, atomicRadius: 190, ionizationEnergy: 684, discoveredBy: "Carl Wilhelm Scheele", yearDiscovered: 1781, uses: ["Steel alloys", "Catalysts", "Lubricants"], funFact: "Molybdenum has one of the highest melting points of all elements!" },
  { number: 43, symbol: "Tc", name: "Technetium", atomic_mass: 98, category: "transition metal", group: 7, period: 5, summary: "Technetium is a chemical element with symbol Tc and atomic number 43.", electron_configuration: "[Kr] 4d5 5s2", xpos: 7, ypos: 5, melt: 2430, boil: 4538, shells: [2, 8, 18, 13, 2], ionCharge: ["+7", "+4"], electronegativity: 1.90, atomicRadius: 183, ionizationEnergy: 702, discoveredBy: "Emilio Segrè", yearDiscovered: 1937, uses: ["Medical imaging", "Nuclear medicine"], funFact: "Technetium was the first artificially produced element!" },
  { number: 44, symbol: "Ru", name: "Ruthenium", atomic_mass: 101.07, category: "transition metal", group: 8, period: 5, summary: "Ruthenium is a chemical element with symbol Ru and atomic number 44.", electron_configuration: "[Kr] 4d7 5s1", xpos: 8, ypos: 5, melt: 2607, boil: 4423, shells: [2, 8, 18, 15, 1], ionCharge: ["+3", "+4"], electronegativity: 2.20, atomicRadius: 178, ionizationEnergy: 710, discoveredBy: "Karl Ernst Claus", yearDiscovered: 1844, uses: ["Electronics", "Catalysts", "Solar cells"], funFact: "Ruthenium is named after Russia (Latin: Ruthenia)." },
  { number: 45, symbol: "Rh", name: "Rhodium", atomic_mass: 102.91, category: "transition metal", group: 9, period: 5, summary: "Rhodium is a chemical element with symbol Rh and atomic number 45.", electron_configuration: "[Kr] 4d8 5s1", xpos: 9, ypos: 5, melt: 2237, boil: 3968, shells: [2, 8, 18, 16, 1], ionCharge: ["+3"], electronegativity: 2.28, atomicRadius: 173, ionizationEnergy: 720, discoveredBy: "William Hyde Wollaston", yearDiscovered: 1803, uses: ["Catalytic converters", "Jewelry", "Mirrors"], funFact: "Rhodium is often the most expensive precious metal, even more than gold!" },
  { number: 46, symbol: "Pd", name: "Palladium", atomic_mass: 106.42, category: "transition metal", group: 10, period: 5, summary: "Palladium is a chemical element with symbol Pd and atomic number 46.", electron_configuration: "[Kr] 4d10", xpos: 10, ypos: 5, melt: 1828.05, boil: 3236, shells: [2, 8, 18, 18], ionCharge: ["+2", "+4"], electronegativity: 2.20, atomicRadius: 169, ionizationEnergy: 804, discoveredBy: "William Hyde Wollaston", yearDiscovered: 1803, uses: ["Catalytic converters", "Jewelry", "Electronics", "Dentistry"], funFact: "Palladium can absorb up to 900 times its own volume of hydrogen!" },
  { number: 47, symbol: "Ag", name: "Silver", atomic_mass: 107.87, category: "transition metal", group: 11, period: 5, summary: "Silver is a chemical element with symbol Ag and atomic number 47.", electron_configuration: "[Kr] 4d10 5s1", xpos: 11, ypos: 5, melt: 1234.93, boil: 2435, shells: [2, 8, 18, 18, 1], ionCharge: ["+1"], electronegativity: 1.93, atomicRadius: 165, ionizationEnergy: 731, discoveredBy: "Ancient", yearDiscovered: "Ancient", uses: ["Jewelry", "Photography", "Electronics", "Medicine"], funFact: "Silver is the best conductor of electricity of all metals!" },
  { number: 48, symbol: "Cd", name: "Cadmium", atomic_mass: 112.41, category: "transition metal", group: 12, period: 5, summary: "Cadmium is a chemical element with symbol Cd and atomic number 48.", electron_configuration: "[Kr] 4d10 5s2", xpos: 12, ypos: 5, melt: 594.22, boil: 1040, shells: [2, 8, 18, 18, 2], ionCharge: ["+2"], electronegativity: 1.69, atomicRadius: 161, ionizationEnergy: 868, discoveredBy: "Karl Samuel Leberecht Hermann", yearDiscovered: 1817, uses: ["Batteries", "Pigments", "Coatings"], funFact: "Cadmium yellow was a favorite pigment of Van Gogh and Monet!" },
  { number: 49, symbol: "In", name: "Indium", atomic_mass: 114.82, category: "post-transition metal", group: 13, period: 5, summary: "Indium is a chemical element with symbol In and atomic number 49.", electron_configuration: "[Kr] 4d10 5s2 5p1", xpos: 13, ypos: 5, melt: 429.75, boil: 2345, shells: [2, 8, 18, 18, 3], ionCharge: ["+3"], electronegativity: 1.78, atomicRadius: 156, ionizationEnergy: 558, discoveredBy: "Ferdinand Reich", yearDiscovered: 1863, uses: ["Touch screens", "Solar cells", "LEDs"], funFact: "Indium makes a 'tin cry' sound when bent, similar to tin." },
  { number: 50, symbol: "Sn", name: "Tin", atomic_mass: 118.71, category: "post-transition metal", group: 14, period: 5, summary: "Tin is a chemical element with symbol Sn and atomic number 50.", electron_configuration: "[Kr] 4d10 5s2 5p2", xpos: 14, ypos: 5, melt: 505.08, boil: 2875, shells: [2, 8, 18, 18, 4], ionCharge: ["+4", "+2"], electronegativity: 1.96, atomicRadius: 145, ionizationEnergy: 709, discoveredBy: "Ancient", yearDiscovered: "Ancient", uses: ["Tin cans", "Solder", "Bronze", "Glass coatings"], funFact: "The Bronze Age was named for the alloy of copper and tin!" },
  { number: 51, symbol: "Sb", name: "Antimony", atomic_mass: 121.76, category: "metalloid", group: 15, period: 5, summary: "Antimony is a chemical element with symbol Sb and atomic number 51.", electron_configuration: "[Kr] 4d10 5s2 5p3", xpos: 15, ypos: 5, melt: 903.78, boil: 1908, shells: [2, 8, 18, 18, 5], ionCharge: ["+5", "+3", "-3"], electronegativity: 2.05, atomicRadius: 133, ionizationEnergy: 834, discoveredBy: "Ancient", yearDiscovered: "Ancient", uses: ["Flame retardants", "Batteries", "Semiconductors"], funFact: "Ancient Egyptians used antimony compounds as eye makeup!" },
  { number: 52, symbol: "Te", name: "Tellurium", atomic_mass: 127.6, category: "metalloid", group: 16, period: 5, summary: "Tellurium is a chemical element with symbol Te and atomic number 52.", electron_configuration: "[Kr] 4d10 5s2 5p4", xpos: 16, ypos: 5, melt: 722.66, boil: 1261, shells: [2, 8, 18, 18, 6], ionCharge: ["+6", "+4", "-2"], electronegativity: 2.10, atomicRadius: 123, ionizationEnergy: 869, discoveredBy: "Franz-Joseph Müller von Reichenstein", yearDiscovered: 1782, uses: ["Solar cells", "Thermoelectric devices", "Alloys"], funFact: "Exposure to tellurium causes garlic-like breath odor!" },
  { number: 53, symbol: "I", name: "Iodine", atomic_mass: 126.9, category: "diatomic nonmetal", group: 17, period: 5, summary: "Iodine is a chemical element with symbol I and atomic number 53.", electron_configuration: "[Kr] 4d10 5s2 5p5", xpos: 17, ypos: 5, melt: 386.85, boil: 457.4, shells: [2, 8, 18, 18, 7], ionCharge: ["-1", "+1", "+5", "+7"], electronegativity: 2.66, atomicRadius: 115, ionizationEnergy: 1008, discoveredBy: "Bernard Courtois", yearDiscovered: 1811, uses: ["Disinfectants", "Thyroid medicine", "Photography", "Salt additive"], funFact: "Iodine deficiency is the leading cause of preventable mental disability worldwide." },
  { number: 54, symbol: "Xe", name: "Xenon", atomic_mass: 131.29, category: "noble gas", group: 18, period: 5, summary: "Xenon is a chemical element with symbol Xe and atomic number 54.", electron_configuration: "[Kr] 4d10 5s2 5p6", xpos: 18, ypos: 5, melt: 161.4, boil: 165.051, shells: [2, 8, 18, 18, 8], ionCharge: ["0", "+2", "+4", "+6"], electronegativity: 2.60, atomicRadius: 108, ionizationEnergy: 1170, discoveredBy: "William Ramsay", yearDiscovered: 1898, uses: ["Headlights", "Anesthesia", "Ion propulsion", "Medical imaging"], funFact: "Xenon was the first noble gas found to form true chemical compounds!" },
  { number: 55, symbol: "Cs", name: "Caesium", atomic_mass: 132.91, category: "alkali metal", group: 1, period: 6, summary: "Caesium is a chemical element with symbol Cs and atomic number 55.", electron_configuration: "[Xe] 6s1", xpos: 1, ypos: 6, melt: 301.7, boil: 944, shells: [2, 8, 18, 18, 8, 1], ionCharge: ["+1"], electronegativity: 0.79, atomicRadius: 298, ionizationEnergy: 376, discoveredBy: "Robert Bunsen", yearDiscovered: 1860, uses: ["Atomic clocks", "Drilling fluids", "Ion propulsion"], funFact: "Caesium atomic clocks are so accurate they lose only 1 second every 300 million years!" },
  { number: 56, symbol: "Ba", name: "Barium", atomic_mass: 137.33, category: "alkaline earth metal", group: 2, period: 6, summary: "Barium is a chemical element with symbol Ba and atomic number 56.", electron_configuration: "[Xe] 6s2", xpos: 2, ypos: 6, melt: 1000, boil: 2118, shells: [2, 8, 18, 18, 8, 2], ionCharge: ["+2"], electronegativity: 0.89, atomicRadius: 253, ionizationEnergy: 503, discoveredBy: "Carl Wilhelm Scheele", yearDiscovered: 1772, uses: ["X-ray imaging", "Fireworks (green)", "Glass making"], funFact: "Barium 'milkshakes' help doctors see your digestive system in X-rays!" },
  { number: 57, symbol: "La", name: "Lanthanum", atomic_mass: 138.91, category: "lanthanide", group: 3, period: 6, summary: "Lanthanum is a chemical element with symbol La and atomic number 57.", electron_configuration: "[Xe] 5d1 6s2", xpos: 3, ypos: 9, melt: 1193, boil: 3737, shells: [2, 8, 18, 18, 9, 2], ionCharge: ["+3"], electronegativity: 1.10, atomicRadius: 195, ionizationEnergy: 538, discoveredBy: "Carl Gustaf Mosander", yearDiscovered: 1839, uses: ["Camera lenses", "Batteries", "Catalysts"], funFact: "Lanthanum is the first of the 'lanthanides' or rare earth elements!" },
  { number: 58, symbol: "Ce", name: "Cerium", atomic_mass: 140.12, category: "lanthanide", group: 3, period: 6, summary: "Cerium is a chemical element with symbol Ce and atomic number 58.", electron_configuration: "[Xe] 4f1 5d1 6s2", xpos: 4, ypos: 9, melt: 1068, boil: 3716, shells: [2, 8, 18, 19, 9, 2], ionCharge: ["+4", "+3"], electronegativity: 1.12, atomicRadius: 185, ionizationEnergy: 534, discoveredBy: "Martin Heinrich Klaproth", yearDiscovered: 1803, uses: ["Catalytic converters", "Self-cleaning ovens", "Lighter flints"], funFact: "Cerium is the most abundant of all the rare earth elements!" },
  { number: 59, symbol: "Pr", name: "Praseodymium", atomic_mass: 140.91, category: "lanthanide", group: 3, period: 6, summary: "Praseodymium is a chemical element with symbol Pr and atomic number 59.", electron_configuration: "[Xe] 4f3 6s2", xpos: 5, ypos: 9, melt: 1208, boil: 3403, shells: [2, 8, 18, 21, 8, 2], ionCharge: ["+3", "+4"], electronegativity: 1.13, atomicRadius: 247, ionizationEnergy: 527, discoveredBy: "Carl Auer von Welsbach", yearDiscovered: 1885, uses: ["Magnets", "Lasers", "Aircraft engines"], funFact: "Praseodymium means 'green twin' in Greek due to its green salts." },
  { number: 60, symbol: "Nd", name: "Neodymium", atomic_mass: 144.24, category: "lanthanide", group: 3, period: 6, summary: "Neodymium is a chemical element with symbol Nd and atomic number 60.", electron_configuration: "[Xe] 4f4 6s2", xpos: 6, ypos: 9, melt: 1297, boil: 3347, shells: [2, 8, 18, 22, 8, 2], ionCharge: ["+3"], electronegativity: 1.14, atomicRadius: 206, ionizationEnergy: 533, discoveredBy: "Carl Auer von Welsbach", yearDiscovered: 1885, uses: ["Powerful magnets", "Lasers", "Glass coloring"], funFact: "Neodymium magnets are the strongest permanent magnets in the world!" },
  { number: 61, symbol: "Pm", name: "Promethium", atomic_mass: 145, category: "lanthanide", group: 3, period: 6, summary: "Promethium is a chemical element with symbol Pm and atomic number 61.", electron_configuration: "[Xe] 4f5 6s2", xpos: 7, ypos: 9, melt: 1315, boil: 3273, shells: [2, 8, 18, 23, 8, 2], ionCharge: ["+3"], electronegativity: 1.13, atomicRadius: 205, ionizationEnergy: 540, discoveredBy: "Chien Shiung Wu", yearDiscovered: 1945, uses: ["Nuclear batteries", "Luminous paint"], funFact: "Promethium is the only radioactive rare earth element with no stable isotopes!" },
  { number: 62, symbol: "Sm", name: "Samarium", atomic_mass: 150.36, category: "lanthanide", group: 3, period: 6, summary: "Samarium is a chemical element with symbol Sm and atomic number 62.", electron_configuration: "[Xe] 4f6 6s2", xpos: 8, ypos: 9, melt: 1345, boil: 2173, shells: [2, 8, 18, 24, 8, 2], ionCharge: ["+3", "+2"], electronegativity: 1.17, atomicRadius: 238, ionizationEnergy: 545, discoveredBy: "Lecoq de Boisbaudran", yearDiscovered: 1879, uses: ["Magnets", "Cancer treatment", "Reactor control rods"], funFact: "Samarium-cobalt magnets were the first rare earth magnets developed!" },
  { number: 63, symbol: "Eu", name: "Europium", atomic_mass: 151.96, category: "lanthanide", group: 3, period: 6, summary: "Europium is a chemical element with symbol Eu and atomic number 63.", electron_configuration: "[Xe] 4f7 6s2", xpos: 9, ypos: 9, melt: 1099, boil: 1802, shells: [2, 8, 18, 25, 8, 2], ionCharge: ["+3", "+2"], electronegativity: 1.20, atomicRadius: 231, ionizationEnergy: 547, discoveredBy: "Eugène-Anatole Demarçay", yearDiscovered: 1901, uses: ["TV screens (red)", "Euro banknote security", "Fluorescent lamps"], funFact: "Europium is used in anti-counterfeiting marks on Euro banknotes!" },
  { number: 64, symbol: "Gd", name: "Gadolinium", atomic_mass: 157.25, category: "lanthanide", group: 3, period: 6, summary: "Gadolinium is a chemical element with symbol Gd and atomic number 64.", electron_configuration: "[Xe] 4f7 5d1 6s2", xpos: 10, ypos: 9, melt: 1585, boil: 3546, shells: [2, 8, 18, 25, 9, 2], ionCharge: ["+3"], electronegativity: 1.20, atomicRadius: 233, ionizationEnergy: 593, discoveredBy: "Jean Charles Galissard de Marignac", yearDiscovered: 1880, uses: ["MRI contrast agent", "Nuclear reactors", "Refrigeration"], funFact: "Gadolinium is used in MRI scans to help doctors see clearer images!" },
  { number: 65, symbol: "Tb", name: "Terbium", atomic_mass: 158.93, category: "lanthanide", group: 3, period: 6, summary: "Terbium is a chemical element with symbol Tb and atomic number 65.", electron_configuration: "[Xe] 4f9 6s2", xpos: 11, ypos: 9, melt: 1629, boil: 3503, shells: [2, 8, 18, 27, 8, 2], ionCharge: ["+3", "+4"], electronegativity: 1.20, atomicRadius: 225, ionizationEnergy: 566, discoveredBy: "Carl Gustaf Mosander", yearDiscovered: 1843, uses: ["Green phosphors", "Sonar systems", "Fuel cells"], funFact: "Terbium is named after Ytterby, Sweden - one of 4 elements from that village!" },
  { number: 66, symbol: "Dy", name: "Dysprosium", atomic_mass: 162.50, category: "lanthanide", group: 3, period: 6, summary: "Dysprosium is a chemical element with symbol Dy and atomic number 66.", electron_configuration: "[Xe] 4f10 6s2", xpos: 12, ypos: 9, melt: 1680, boil: 2840, shells: [2, 8, 18, 28, 8, 2], ionCharge: ["+3"], electronegativity: 1.22, atomicRadius: 228, ionizationEnergy: 573, discoveredBy: "Lecoq de Boisbaudran", yearDiscovered: 1886, uses: ["Magnets", "Lasers", "Data storage"], funFact: "Dysprosium means 'hard to get' in Greek - it's very difficult to isolate!" },
  { number: 67, symbol: "Ho", name: "Holmium", atomic_mass: 164.93, category: "lanthanide", group: 3, period: 6, summary: "Holmium is a chemical element with symbol Ho and atomic number 67.", electron_configuration: "[Xe] 4f11 6s2", xpos: 13, ypos: 9, melt: 1734, boil: 2873, shells: [2, 8, 18, 29, 8, 2], ionCharge: ["+3"], electronegativity: 1.23, atomicRadius: 226, ionizationEnergy: 581, discoveredBy: "Marc Delafontaine", yearDiscovered: 1878, uses: ["Magnets", "Nuclear reactors", "Medical lasers"], funFact: "Holmium has the highest magnetic strength of any element!" },
  { number: 68, symbol: "Er", name: "Erbium", atomic_mass: 167.26, category: "lanthanide", group: 3, period: 6, summary: "Erbium is a chemical element with symbol Er and atomic number 68.", electron_configuration: "[Xe] 4f12 6s2", xpos: 14, ypos: 9, melt: 1802, boil: 3141, shells: [2, 8, 18, 30, 8, 2], ionCharge: ["+3"], electronegativity: 1.24, atomicRadius: 226, ionizationEnergy: 589, discoveredBy: "Carl Gustaf Mosander", yearDiscovered: 1843, uses: ["Fiber optics", "Lasers", "Glass coloring"], funFact: "Erbium-doped fiber amplifiers revolutionized long-distance communication!" },
  { number: 69, symbol: "Tm", name: "Thulium", atomic_mass: 168.93, category: "lanthanide", group: 3, period: 6, summary: "Thulium is a chemical element with symbol Tm and atomic number 69.", electron_configuration: "[Xe] 4f13 6s2", xpos: 15, ypos: 9, melt: 1818, boil: 2223, shells: [2, 8, 18, 31, 8, 2], ionCharge: ["+3", "+2"], electronegativity: 1.25, atomicRadius: 222, ionizationEnergy: 597, discoveredBy: "Per Teodor Cleve", yearDiscovered: 1879, uses: ["Portable X-ray machines", "Lasers"], funFact: "Thulium is the rarest of the rare earth elements (excluding promethium)!" },
  { number: 70, symbol: "Yb", name: "Ytterbium", atomic_mass: 173.05, category: "lanthanide", group: 3, period: 6, summary: "Ytterbium is a chemical element with symbol Yb and atomic number 70.", electron_configuration: "[Xe] 4f14 6s2", xpos: 16, ypos: 9, melt: 1097, boil: 1469, shells: [2, 8, 18, 32, 8, 2], ionCharge: ["+3", "+2"], electronegativity: 1.10, atomicRadius: 222, ionizationEnergy: 603, discoveredBy: "Jean Charles Galissard de Marignac", yearDiscovered: 1878, uses: ["Lasers", "Metallurgy", "Atomic clocks"], funFact: "Ytterbium is the third element named after Ytterby, Sweden!" },
  { number: 71, symbol: "Lu", name: "Lutetium", atomic_mass: 174.97, category: "lanthanide", group: 3, period: 6, summary: "Lutetium is a chemical element with symbol Lu and atomic number 71.", electron_configuration: "[Xe] 4f14 5d1 6s2", xpos: 17, ypos: 9, melt: 1925, boil: 3675, shells: [2, 8, 18, 32, 9, 2], ionCharge: ["+3"], electronegativity: 1.27, atomicRadius: 217, ionizationEnergy: 524, discoveredBy: "Georges Urbain", yearDiscovered: 1907, uses: ["PET scan detectors", "Catalysts", "Dating meteorites"], funFact: "Lutetium is named after Lutetia, the Latin name for Paris!" },
  { number: 72, symbol: "Hf", name: "Hafnium", atomic_mass: 178.49, category: "transition metal", group: 4, period: 6, summary: "Hafnium is a chemical element with symbol Hf and atomic number 72.", electron_configuration: "[Xe] 4f14 5d2 6s2", xpos: 4, ypos: 6, melt: 2506, boil: 4876, shells: [2, 8, 18, 32, 10, 2], ionCharge: ["+4"], electronegativity: 1.30, atomicRadius: 208, ionizationEnergy: 659, discoveredBy: "Dirk Coster", yearDiscovered: 1923, uses: ["Nuclear reactors", "Plasma cutting", "Microprocessors"], funFact: "Hafnium is named after Copenhagen (Latin: Hafnia) where it was discovered!" },
  { number: 73, symbol: "Ta", name: "Tantalum", atomic_mass: 180.95, category: "transition metal", group: 5, period: 6, summary: "Tantalum is a chemical element with symbol Ta and atomic number 73.", electron_configuration: "[Xe] 4f14 5d3 6s2", xpos: 5, ypos: 6, melt: 3290, boil: 5731, shells: [2, 8, 18, 32, 11, 2], ionCharge: ["+5"], electronegativity: 1.50, atomicRadius: 200, ionizationEnergy: 761, discoveredBy: "Anders Gustaf Ekeberg", yearDiscovered: 1802, uses: ["Capacitors", "Medical implants", "Jet engines"], funFact: "Tantalum is used in virtually every smartphone and laptop!" },
  { number: 74, symbol: "W", name: "Tungsten", atomic_mass: 183.84, category: "transition metal", group: 6, period: 6, summary: "Tungsten is a chemical element with symbol W and atomic number 74.", electron_configuration: "[Xe] 4f14 5d4 6s2", xpos: 6, ypos: 6, melt: 3695, boil: 6203, shells: [2, 8, 18, 32, 12, 2], ionCharge: ["+6", "+4"], electronegativity: 2.36, atomicRadius: 193, ionizationEnergy: 770, discoveredBy: "Carl Wilhelm Scheele", yearDiscovered: 1783, uses: ["Light bulb filaments", "Cutting tools", "Radiation shielding"], funFact: "Tungsten has the highest melting point of all elements at 3422°C!" },
  { number: 75, symbol: "Re", name: "Rhenium", atomic_mass: 186.21, category: "transition metal", group: 7, period: 6, summary: "Rhenium is a chemical element with symbol Re and atomic number 75.", electron_configuration: "[Xe] 4f14 5d5 6s2", xpos: 7, ypos: 6, melt: 3459, boil: 5869, shells: [2, 8, 18, 32, 13, 2], ionCharge: ["+7", "+4"], electronegativity: 1.90, atomicRadius: 188, ionizationEnergy: 760, discoveredBy: "Masataka Ogawa", yearDiscovered: 1925, uses: ["Jet engines", "Catalysts", "Thermocouples"], funFact: "Rhenium was one of the last stable elements to be discovered!" },
  { number: 76, symbol: "Os", name: "Osmium", atomic_mass: 190.23, category: "transition metal", group: 8, period: 6, summary: "Osmium is a chemical element with symbol Os and atomic number 76.", electron_configuration: "[Xe] 4f14 5d6 6s2", xpos: 8, ypos: 6, melt: 3306, boil: 5285, shells: [2, 8, 18, 32, 14, 2], ionCharge: ["+4", "+3"], electronegativity: 2.20, atomicRadius: 185, ionizationEnergy: 840, discoveredBy: "Smithson Tennant", yearDiscovered: 1803, uses: ["Fountain pen tips", "Electrical contacts", "Fingerprint detection"], funFact: "Osmium is the densest naturally occurring element!" },
  { number: 77, symbol: "Ir", name: "Iridium", atomic_mass: 192.22, category: "transition metal", group: 9, period: 6, summary: "Iridium is a chemical element with symbol Ir and atomic number 77.", electron_configuration: "[Xe] 4f14 5d7 6s2", xpos: 9, ypos: 6, melt: 2719, boil: 4403, shells: [2, 8, 18, 32, 15, 2], ionCharge: ["+4", "+3"], electronegativity: 2.20, atomicRadius: 180, ionizationEnergy: 880, discoveredBy: "Smithson Tennant", yearDiscovered: 1803, uses: ["Spark plugs", "Crucibles", "Fountain pen nibs"], funFact: "An iridium layer in rocks marks the asteroid impact that killed the dinosaurs!" },
  { number: 78, symbol: "Pt", name: "Platinum", atomic_mass: 195.08, category: "transition metal", group: 10, period: 6, summary: "Platinum is a chemical element with symbol Pt and atomic number 78.", electron_configuration: "[Xe] 4f14 5d9 6s1", xpos: 10, ypos: 6, melt: 2041.4, boil: 4098, shells: [2, 8, 18, 32, 17, 1], ionCharge: ["+4", "+2"], electronegativity: 2.28, atomicRadius: 177, ionizationEnergy: 870, discoveredBy: "Antonio de Ulloa", yearDiscovered: 1735, uses: ["Jewelry", "Catalytic converters", "Chemotherapy drugs"], funFact: "All the platinum ever mined would fit in an average living room!" },
  { number: 79, symbol: "Au", name: "Gold", atomic_mass: 196.97, category: "transition metal", group: 11, period: 6, summary: "Gold is a chemical element with symbol Au and atomic number 79.", electron_configuration: "[Xe] 4f14 5d10 6s1", xpos: 11, ypos: 6, melt: 1337.33, boil: 3243, shells: [2, 8, 18, 32, 18, 1], ionCharge: ["+3", "+1"], electronegativity: 2.54, atomicRadius: 174, ionizationEnergy: 890, discoveredBy: "Ancient", yearDiscovered: "Ancient", uses: ["Jewelry", "Electronics", "Dentistry", "Currency"], funFact: "All the gold ever mined would fit into a cube of just 21 meters per side!" },
  { number: 80, symbol: "Hg", name: "Mercury", atomic_mass: 200.59, category: "transition metal", group: 12, period: 6, summary: "Mercury is a chemical element with symbol Hg and atomic number 80.", electron_configuration: "[Xe] 4f14 5d10 6s2", xpos: 12, ypos: 6, melt: 234.32, boil: 629.88, shells: [2, 8, 18, 32, 18, 2], ionCharge: ["+2", "+1"], electronegativity: 2.00, atomicRadius: 171, ionizationEnergy: 1007, discoveredBy: "Ancient", yearDiscovered: "Ancient", uses: ["Thermometers", "Barometers", "Fluorescent lights"], funFact: "Mercury is the only metal that is liquid at room temperature!" },
  { number: 81, symbol: "Tl", name: "Thallium", atomic_mass: 204.38, category: "post-transition metal", group: 13, period: 6, summary: "Thallium is a chemical element with symbol Tl and atomic number 81.", electron_configuration: "[Xe] 4f14 5d10 6s2 6p1", xpos: 13, ypos: 6, melt: 577, boil: 1746, shells: [2, 8, 18, 32, 18, 3], ionCharge: ["+3", "+1"], electronegativity: 1.62, atomicRadius: 156, ionizationEnergy: 589, discoveredBy: "William Crookes", yearDiscovered: 1861, uses: ["Electronics", "Medical imaging", "Rat poison (historical)"], funFact: "Thallium was once used in murder cases due to being tasteless and odorless!" },
  { number: 82, symbol: "Pb", name: "Lead", atomic_mass: 207.2, category: "post-transition metal", group: 14, period: 6, summary: "Lead is a chemical element with symbol Pb and atomic number 82.", electron_configuration: "[Xe] 4f14 5d10 6s2 6p2", xpos: 14, ypos: 6, melt: 600.61, boil: 2022, shells: [2, 8, 18, 32, 18, 4], ionCharge: ["+4", "+2"], electronegativity: 1.87, atomicRadius: 154, ionizationEnergy: 716, discoveredBy: "Ancient", yearDiscovered: "Ancient", uses: ["Batteries", "Radiation shielding", "Weights"], funFact: "Ancient Romans used lead pipes for water - the word 'plumber' comes from 'plumbum' (lead)!" },
  { number: 83, symbol: "Bi", name: "Bismuth", atomic_mass: 208.98, category: "post-transition metal", group: 15, period: 6, summary: "Bismuth is a chemical element with symbol Bi and atomic number 83.", electron_configuration: "[Xe] 4f14 5d10 6s2 6p3", xpos: 15, ypos: 6, melt: 544.7, boil: 1837, shells: [2, 8, 18, 32, 18, 5], ionCharge: ["+5", "+3"], electronegativity: 2.02, atomicRadius: 143, ionizationEnergy: 703, discoveredBy: "Claude François Geoffroy", yearDiscovered: 1753, uses: ["Medicine (Pepto-Bismol)", "Cosmetics", "Fire detectors", "Low-melt alloys"], funFact: "Bismuth crystals form beautiful rainbow-colored hopper structures!" },
  { number: 84, symbol: "Po", name: "Polonium", atomic_mass: 209, category: "post-transition metal", group: 16, period: 6, summary: "Polonium is a chemical element with symbol Po and atomic number 84.", electron_configuration: "[Xe] 4f14 5d10 6s2 6p4", xpos: 16, ypos: 6, melt: 527, boil: 1235, shells: [2, 8, 18, 32, 18, 6], ionCharge: ["+4", "+2"], electronegativity: 2.00, atomicRadius: 135, ionizationEnergy: 812, discoveredBy: "Marie Curie", yearDiscovered: 1898, uses: ["Static eliminators", "Heat sources", "Research"], funFact: "Polonium was named after Poland, Marie Curie's homeland!" },
  { number: 85, symbol: "At", name: "Astatine", atomic_mass: 210, category: "metalloid", group: 17, period: 6, summary: "Astatine is a radioactive chemical element with symbol At and atomic number 85.", electron_configuration: "[Xe] 4f14 5d10 6s2 6p5", xpos: 17, ypos: 6, melt: 575, boil: 610, shells: [2, 8, 18, 32, 18, 7], ionCharge: ["-1", "+1"], electronegativity: 2.20, atomicRadius: 127, ionizationEnergy: 920, discoveredBy: "Dale R. Corson", yearDiscovered: 1940, uses: ["Cancer treatment research"], funFact: "Astatine is the rarest naturally occurring element on Earth - only about 25 grams exist at any time!" },
  { number: 86, symbol: "Rn", name: "Radon", atomic_mass: 222, category: "noble gas", group: 18, period: 6, summary: "Radon is a chemical element with symbol Rn and atomic number 86.", electron_configuration: "[Xe] 4f14 5d10 6s2 6p6", xpos: 18, ypos: 6, melt: 202, boil: 211.5, shells: [2, 8, 18, 32, 18, 8], ionCharge: ["0"], electronegativity: 2.20, atomicRadius: 120, ionizationEnergy: 1037, discoveredBy: "Friedrich Ernst Dorn", yearDiscovered: 1900, uses: ["Earthquake prediction research", "Radon therapy (historical)"], funFact: "Radon is the leading cause of lung cancer among non-smokers!" },
  { number: 87, symbol: "Fr", name: "Francium", atomic_mass: 223, category: "alkali metal", group: 1, period: 7, summary: "Francium is a chemical element with symbol Fr and atomic number 87.", electron_configuration: "[Rn] 7s1", xpos: 1, ypos: 7, melt: 300, boil: 950, shells: [2, 8, 18, 32, 18, 8, 1], ionCharge: ["+1"], electronegativity: 0.70, atomicRadius: 348, ionizationEnergy: 380, discoveredBy: "Marguerite Perey", yearDiscovered: 1939, uses: ["Research only"], funFact: "Francium is the most unstable of the first 101 elements - it has a half-life of just 22 minutes!" },
  { number: 88, symbol: "Ra", name: "Radium", atomic_mass: 226, category: "alkaline earth metal", group: 2, period: 7, summary: "Radium is a chemical element with symbol Ra and atomic number 88.", electron_configuration: "[Rn] 7s2", xpos: 2, ypos: 7, melt: 973, boil: 2010, shells: [2, 8, 18, 32, 18, 8, 2], ionCharge: ["+2"], electronegativity: 0.90, atomicRadius: 283, ionizationEnergy: 509, discoveredBy: "Pierre and Marie Curie", yearDiscovered: 1898, uses: ["Cancer treatment (historical)", "Luminous paint (historical)"], funFact: "Radium glows in the dark - it was once used in watch dials until its dangers were discovered!" },
  { number: 89, symbol: "Ac", name: "Actinium", atomic_mass: 227, category: "actinide", group: 3, period: 7, summary: "Actinium is a radioactive chemical element with symbol Ac and atomic number 89.", electron_configuration: "[Rn] 6d1 7s2", xpos: 3, ypos: 10, melt: 1500, boil: 3500, shells: [2, 8, 18, 32, 18, 9, 2], ionCharge: ["+3"], electronegativity: 1.10, atomicRadius: 260, ionizationEnergy: 499, discoveredBy: "Friedrich Oskar Giesel", yearDiscovered: 1899, uses: ["Neutron sources", "Cancer treatment research"], funFact: "Actinium glows blue in the dark due to its intense radioactivity!" },
  { number: 90, symbol: "Th", name: "Thorium", atomic_mass: 232.04, category: "actinide", group: 3, period: 7, summary: "Thorium is a chemical element with symbol Th and atomic number 90.", electron_configuration: "[Rn] 6d2 7s2", xpos: 4, ypos: 10, melt: 2023, boil: 5061, shells: [2, 8, 18, 32, 18, 10, 2], ionCharge: ["+4"], electronegativity: 1.30, atomicRadius: 237, ionizationEnergy: 587, discoveredBy: "Jöns Jacob Berzelius", yearDiscovered: 1829, uses: ["Nuclear fuel", "Gas mantles", "Welding electrodes"], funFact: "Thorium could power nuclear reactors with less waste than uranium!" },
  { number: 91, symbol: "Pa", name: "Protactinium", atomic_mass: 231.04, category: "actinide", group: 3, period: 7, summary: "Protactinium is a chemical element with symbol Pa and atomic number 91.", electron_configuration: "[Rn] 5f2 6d1 7s2", xpos: 5, ypos: 10, melt: 1841, boil: 4300, shells: [2, 8, 18, 32, 20, 9, 2], ionCharge: ["+5", "+4"], electronegativity: 1.50, atomicRadius: 243, ionizationEnergy: 568, discoveredBy: "William Crookes", yearDiscovered: 1913, uses: ["Research only"], funFact: "Protactinium is one of the rarest and most expensive naturally occurring elements!" },
  { number: 92, symbol: "U", name: "Uranium", atomic_mass: 238.03, category: "actinide", group: 3, period: 7, summary: "Uranium is a chemical element with symbol U and atomic number 92.", electron_configuration: "[Rn] 5f3 6d1 7s2", xpos: 6, ypos: 10, melt: 1405.3, boil: 4404, shells: [2, 8, 18, 32, 21, 9, 2], ionCharge: ["+6", "+4", "+3"], electronegativity: 1.38, atomicRadius: 240, ionizationEnergy: 598, discoveredBy: "Martin Heinrich Klaproth", yearDiscovered: 1789, uses: ["Nuclear fuel", "Nuclear weapons", "Counterweights", "Armor-piercing ammunition"], funFact: "A pellet of uranium fuel the size of your fingertip contains as much energy as 17,000 cubic feet of natural gas!" },
  { number: 93, symbol: "Np", name: "Neptunium", atomic_mass: 237, category: "actinide", group: 3, period: 7, summary: "Neptunium is a chemical element with symbol Np and atomic number 93.", electron_configuration: "[Rn] 5f4 6d1 7s2", xpos: 7, ypos: 10, melt: 912, boil: 4447, shells: [2, 8, 18, 32, 22, 9, 2], ionCharge: ["+5", "+4", "+3"], electronegativity: 1.36, atomicRadius: 221, ionizationEnergy: 605, discoveredBy: "Edwin McMillan", yearDiscovered: 1940, uses: ["Neutron detectors", "Research"], funFact: "Neptunium was the first transuranium element ever discovered!" },
  { number: 94, symbol: "Pu", name: "Plutonium", atomic_mass: 244, category: "actinide", group: 3, period: 7, summary: "Plutonium is a radioactive chemical element with symbol Pu and atomic number 94.", electron_configuration: "[Rn] 5f6 7s2", xpos: 8, ypos: 10, melt: 912.5, boil: 3505, shells: [2, 8, 18, 32, 24, 8, 2], ionCharge: ["+4", "+3", "+5", "+6"], electronegativity: 1.28, atomicRadius: 243, ionizationEnergy: 585, discoveredBy: "Glenn T. Seaborg", yearDiscovered: 1940, uses: ["Nuclear weapons", "Nuclear reactors", "Space probe power"], funFact: "Plutonium powered the Voyager spacecraft that left our solar system!" },
  { number: 95, symbol: "Am", name: "Americium", atomic_mass: 243, category: "actinide", group: 3, period: 7, summary: "Americium is a radioactive chemical element with symbol Am and atomic number 95.", electron_configuration: "[Rn] 5f7 7s2", xpos: 9, ypos: 10, melt: 1449, boil: 2880, shells: [2, 8, 18, 32, 25, 8, 2], ionCharge: ["+3", "+4"], electronegativity: 1.30, atomicRadius: 244, ionizationEnergy: 578, discoveredBy: "Glenn T. Seaborg", yearDiscovered: 1944, uses: ["Smoke detectors", "Industrial gauges"], funFact: "Your smoke detector probably contains americium-241!" },
  { number: 96, symbol: "Cm", name: "Curium", atomic_mass: 247, category: "actinide", group: 3, period: 7, summary: "Curium is a radioactive chemical element with symbol Cm and atomic number 96.", electron_configuration: "[Rn] 5f7 6d1 7s2", xpos: 10, ypos: 10, melt: 1613, boil: 3383, shells: [2, 8, 18, 32, 25, 9, 2], ionCharge: ["+3"], electronegativity: 1.30, atomicRadius: 245, ionizationEnergy: 581, discoveredBy: "Glenn T. Seaborg", yearDiscovered: 1944, uses: ["Space probe power", "Research"], funFact: "Curium is named after Marie and Pierre Curie, pioneers of radioactivity research!" },
  { number: 97, symbol: "Bk", name: "Berkelium", atomic_mass: 247, category: "actinide", group: 3, period: 7, summary: "Berkelium is a radioactive chemical element with symbol Bk and atomic number 97.", electron_configuration: "[Rn] 5f9 7s2", xpos: 11, ypos: 10, melt: 1259, boil: 2900, shells: [2, 8, 18, 32, 27, 8, 2], ionCharge: ["+3", "+4"], electronegativity: 1.30, atomicRadius: 244, ionizationEnergy: 601, discoveredBy: "Lawrence Berkeley National Laboratory", yearDiscovered: 1949, uses: ["Research only"], funFact: "Only about one gram of berkelium has ever been produced!" },
  { number: 98, symbol: "Cf", name: "Californium", atomic_mass: 251, category: "actinide", group: 3, period: 7, summary: "Californium is a radioactive chemical element with symbol Cf and atomic number 98.", electron_configuration: "[Rn] 5f10 7s2", xpos: 12, ypos: 10, melt: 1173, boil: 1743, shells: [2, 8, 18, 32, 28, 8, 2], ionCharge: ["+3"], electronegativity: 1.30, atomicRadius: 245, ionizationEnergy: 608, discoveredBy: "Lawrence Berkeley National Laboratory", yearDiscovered: 1950, uses: ["Neutron sources", "Starting nuclear reactors", "Cancer treatment"], funFact: "Californium-252 costs about $27 million per gram!" },
  { number: 99, symbol: "Es", name: "Einsteinium", atomic_mass: 252, category: "actinide", group: 3, period: 7, summary: "Einsteinium is a synthetic element with symbol Es and atomic number 99.", electron_configuration: "[Rn] 5f11 7s2", xpos: 13, ypos: 10, melt: 1133, boil: 1269, shells: [2, 8, 18, 32, 29, 8, 2], ionCharge: ["+3"], electronegativity: 1.30, atomicRadius: 245, ionizationEnergy: 619, discoveredBy: "Lawrence Berkeley National Laboratory", yearDiscovered: 1952, uses: ["Research only"], funFact: "Einsteinium was first found in the debris of the first hydrogen bomb test!" },
  { number: 100, symbol: "Fm", name: "Fermium", atomic_mass: 257, category: "actinide", group: 3, period: 7, summary: "Fermium is a synthetic element with symbol Fm and atomic number 100.", electron_configuration: "[Rn] 5f12 7s2", xpos: 14, ypos: 10, melt: 1800, boil: undefined, shells: [2, 8, 18, 32, 30, 8, 2], ionCharge: ["+3"], electronegativity: 1.30, atomicRadius: 245, ionizationEnergy: 627, discoveredBy: "Lawrence Berkeley National Laboratory", yearDiscovered: 1952, uses: ["Research only"], funFact: "Fermium is named after Enrico Fermi, creator of the first nuclear reactor!" },
  { number: 101, symbol: "Md", name: "Mendelevium", atomic_mass: 258, category: "actinide", group: 3, period: 7, summary: "Mendelevium is a synthetic element with symbol Md and atomic number 101.", electron_configuration: "[Rn] 5f13 7s2", xpos: 15, ypos: 10, melt: 1100, boil: undefined, shells: [2, 8, 18, 32, 31, 8, 2], ionCharge: ["+3", "+2"], electronegativity: 1.30, atomicRadius: 246, ionizationEnergy: 635, discoveredBy: "Lawrence Berkeley National Laboratory", yearDiscovered: 1955, uses: ["Research only"], funFact: "Mendelevium is named after Dmitri Mendeleev, creator of the periodic table!" },
  { number: 102, symbol: "No", name: "Nobelium", atomic_mass: 259, category: "actinide", group: 3, period: 7, summary: "Nobelium is a synthetic element with symbol No and atomic number 102.", electron_configuration: "[Rn] 5f14 7s2", xpos: 16, ypos: 10, melt: 1100, boil: undefined, shells: [2, 8, 18, 32, 32, 8, 2], ionCharge: ["+3", "+2"], electronegativity: 1.30, atomicRadius: 246, ionizationEnergy: 642, discoveredBy: "Joint Institute for Nuclear Research", yearDiscovered: 1966, uses: ["Research only"], funFact: "Nobelium is named after Alfred Nobel, founder of the Nobel Prizes!" },
  { number: 103, symbol: "Lr", name: "Lawrencium", atomic_mass: 262, category: "actinide", group: 3, period: 7, summary: "Lawrencium is a synthetic element with symbol Lr and atomic number 103.", electron_configuration: "[Rn] 5f14 7s2 7p1", xpos: 17, ypos: 10, melt: 1900, boil: undefined, shells: [2, 8, 18, 32, 32, 8, 3], ionCharge: ["+3"], electronegativity: 1.30, atomicRadius: 246, ionizationEnergy: 479, discoveredBy: "Lawrence Berkeley National Laboratory", yearDiscovered: 1961, uses: ["Research only"], funFact: "Lawrencium is named after Ernest Lawrence, inventor of the cyclotron!" },
  { number: 104, symbol: "Rf", name: "Rutherfordium", atomic_mass: 267, category: "transition metal", group: 4, period: 7, summary: "Rutherfordium is a chemical element with symbol Rf and atomic number 104.", electron_configuration: "[Rn] 5f14 6d2 7s2", xpos: 4, ypos: 7, melt: 2400, boil: 5800, shells: [2, 8, 18, 32, 32, 10, 2], ionCharge: ["+4"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: 580, discoveredBy: "Joint Institute for Nuclear Research", yearDiscovered: 1964, uses: ["Research only"], funFact: "Rutherfordium is named after Ernest Rutherford, father of nuclear physics!" },
  { number: 105, symbol: "Db", name: "Dubnium", atomic_mass: 268, category: "transition metal", group: 5, period: 7, summary: "Dubnium is a chemical element with symbol Db and atomic number 105.", electron_configuration: "[Rn] 5f14 6d3 7s2", xpos: 5, ypos: 7, melt: undefined, boil: undefined, shells: [2, 8, 18, 32, 32, 11, 2], ionCharge: ["+5"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "Lawrence Berkeley National Laboratory", yearDiscovered: 1967, uses: ["Research only"], funFact: "Dubnium is named after Dubna, Russia, home of the Joint Institute for Nuclear Research!" },
  { number: 106, symbol: "Sg", name: "Seaborgium", atomic_mass: 271, category: "transition metal", group: 6, period: 7, summary: "Seaborgium is a chemical element with symbol Sg and atomic number 106.", electron_configuration: "[Rn] 5f14 6d4 7s2", xpos: 6, ypos: 7, melt: undefined, boil: undefined, shells: [2, 8, 18, 32, 32, 12, 2], ionCharge: ["+6"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "Lawrence Berkeley National Laboratory", yearDiscovered: 1974, uses: ["Research only"], funFact: "Seaborgium is named after Glenn T. Seaborg while he was still alive - a first for any element!" },
  { number: 107, symbol: "Bh", name: "Bohrium", atomic_mass: 272, category: "transition metal", group: 7, period: 7, summary: "Bohrium is a chemical element with symbol Bh and atomic number 107.", electron_configuration: "[Rn] 5f14 6d5 7s2", xpos: 7, ypos: 7, melt: undefined, boil: undefined, shells: [2, 8, 18, 32, 32, 13, 2], ionCharge: ["+7"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "Gesellschaft für Schwerionenforschung", yearDiscovered: 1981, uses: ["Research only"], funFact: "Bohrium is named after Niels Bohr, who developed the Bohr model of the atom!" },
  { number: 108, symbol: "Hs", name: "Hassium", atomic_mass: 270, category: "transition metal", group: 8, period: 7, summary: "Hassium is a chemical element with symbol Hs and atomic number 108.", electron_configuration: "[Rn] 5f14 6d6 7s2", xpos: 8, ypos: 7, melt: undefined, boil: undefined, shells: [2, 8, 18, 32, 32, 14, 2], ionCharge: ["+8"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "Gesellschaft für Schwerionenforschung", yearDiscovered: 1984, uses: ["Research only"], funFact: "Hassium is named after Hesse, the German state where it was discovered!" },
  { number: 109, symbol: "Mt", name: "Meitnerium", atomic_mass: 276, category: "unknown", group: 9, period: 7, summary: "Meitnerium is a chemical element with symbol Mt and atomic number 109.", electron_configuration: "[Rn] 5f14 6d7 7s2", xpos: 9, ypos: 7, melt: undefined, boil: undefined, shells: [2, 8, 18, 32, 32, 15, 2], ionCharge: ["+9"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "Gesellschaft für Schwerionenforschung", yearDiscovered: 1982, uses: ["Research only"], funFact: "Meitnerium is named after Lise Meitner, who helped discover nuclear fission!" },
  { number: 110, symbol: "Ds", name: "Darmstadtium", atomic_mass: 281, category: "unknown", group: 10, period: 7, summary: "Darmstadtium is a chemical element with symbol Ds and atomic number 110.", electron_configuration: "[Rn] 5f14 6d9 7s1", xpos: 10, ypos: 7, melt: undefined, boil: undefined, shells: [2, 8, 18, 32, 32, 17, 1], ionCharge: ["+8"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "Gesellschaft für Schwerionenforschung", yearDiscovered: 1994, uses: ["Research only"], funFact: "Darmstadtium is named after Darmstadt, Germany, where it was discovered!" },
  { number: 111, symbol: "Rg", name: "Roentgenium", atomic_mass: 280, category: "unknown", group: 11, period: 7, summary: "Roentgenium is a chemical element with symbol Rg and atomic number 111.", electron_configuration: "[Rn] 5f14 6d10 7s1", xpos: 11, ypos: 7, melt: undefined, boil: undefined, shells: [2, 8, 18, 32, 32, 18, 1], ionCharge: ["+3"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "Gesellschaft für Schwerionenforschung", yearDiscovered: 1994, uses: ["Research only"], funFact: "Roentgenium is named after Wilhelm Röntgen, discoverer of X-rays!" },
  { number: 112, symbol: "Cn", name: "Copernicium", atomic_mass: 285, category: "transition metal", group: 12, period: 7, summary: "Copernicium is a chemical element with symbol Cn and atomic number 112.", electron_configuration: "[Rn] 5f14 6d10 7s2", xpos: 12, ypos: 7, melt: undefined, boil: 357, shells: [2, 8, 18, 32, 32, 18, 2], ionCharge: ["+2"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "Gesellschaft für Schwerionenforschung", yearDiscovered: 1996, uses: ["Research only"], funFact: "Copernicium is named after Nicolaus Copernicus, who proposed the heliocentric model!" },
  { number: 113, symbol: "Nh", name: "Nihonium", atomic_mass: 284, category: "unknown", group: 13, period: 7, summary: "Nihonium is a chemical element with symbol Nh and atomic number 113.", electron_configuration: "[Rn] 5f14 6d10 7s2 7p1", xpos: 13, ypos: 7, melt: 700, boil: 1430, shells: [2, 8, 18, 32, 32, 18, 3], ionCharge: ["+3"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "RIKEN", yearDiscovered: 2004, uses: ["Research only"], funFact: "Nihonium means 'Japan' - it's the first element discovered in Asia!" },
  { number: 114, symbol: "Fl", name: "Flerovium", atomic_mass: 289, category: "post-transition metal", group: 14, period: 7, summary: "Flerovium is a chemical element with symbol Fl and atomic number 114.", electron_configuration: "[Rn] 5f14 6d10 7s2 7p2", xpos: 14, ypos: 7, melt: 340, boil: 420, shells: [2, 8, 18, 32, 32, 18, 4], ionCharge: ["+2"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "Joint Institute for Nuclear Research", yearDiscovered: 1998, uses: ["Research only"], funFact: "Flerovium may behave like a noble gas despite being in group 14!" },
  { number: 115, symbol: "Mc", name: "Moscovium", atomic_mass: 288, category: "unknown", group: 15, period: 7, summary: "Moscovium is a chemical element with symbol Mc and atomic number 115.", electron_configuration: "[Rn] 5f14 6d10 7s2 7p3", xpos: 15, ypos: 7, melt: 700, boil: 1400, shells: [2, 8, 18, 32, 32, 18, 5], ionCharge: ["+3", "+1"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "Joint Institute for Nuclear Research", yearDiscovered: 2003, uses: ["Research only"], funFact: "Moscovium is named after Moscow, home of the research institute that helped discover it!" },
  { number: 116, symbol: "Lv", name: "Livermorium", atomic_mass: 293, category: "unknown", group: 16, period: 7, summary: "Livermorium is a chemical element with symbol Lv and atomic number 116.", electron_configuration: "[Rn] 5f14 6d10 7s2 7p4", xpos: 16, ypos: 7, melt: 709, boil: 1085, shells: [2, 8, 18, 32, 32, 18, 6], ionCharge: ["+4", "+2"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "Joint Institute for Nuclear Research", yearDiscovered: 2000, uses: ["Research only"], funFact: "Livermorium is named after Lawrence Livermore National Laboratory in California!" },
  { number: 117, symbol: "Ts", name: "Tennessine", atomic_mass: 294, category: "unknown", group: 17, period: 7, summary: "Tennessine is a chemical element with symbol Ts and atomic number 117.", electron_configuration: "[Rn] 5f14 6d10 7s2 7p5", xpos: 17, ypos: 7, melt: 723, boil: 883, shells: [2, 8, 18, 32, 32, 18, 7], ionCharge: ["-1", "+1"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "Joint Institute for Nuclear Research", yearDiscovered: 2010, uses: ["Research only"], funFact: "Tennessine is named after Tennessee, home to Oak Ridge National Laboratory!" },
  { number: 118, symbol: "Og", name: "Oganesson", atomic_mass: 294, category: "unknown", group: 18, period: 7, summary: "Oganesson is a chemical element with symbol Og and atomic number 118.", electron_configuration: "[Rn] 5f14 6d10 7s2 7p6", xpos: 18, ypos: 7, melt: 325, boil: 450, shells: [2, 8, 18, 32, 32, 18, 8], ionCharge: ["0"], electronegativity: undefined, atomicRadius: undefined, ionizationEnergy: undefined, discoveredBy: "Joint Institute for Nuclear Research", yearDiscovered: 2002, uses: ["Research only"], funFact: "Oganesson is named after Yuri Oganessian, a pioneer in superheavy element research - one of only two elements named after a living person!" }
];

export const categories = [
  "alkali metal",
  "alkaline earth metal",
  "lanthanide",
  "actinide",
  "transition metal",
  "post-transition metal",
  "metalloid",
  "diatomic nonmetal",
  "polyatomic nonmetal",
  "noble gas",
  "unknown"
];

export const categoryColors: Record<string, string> = {
  "alkali metal": "bg-red-100 border-red-400 text-red-900",
  "alkaline earth metal": "bg-orange-100 border-orange-400 text-orange-900",
  "lanthanide": "bg-pink-100 border-pink-400 text-pink-900",
  "actinide": "bg-fuchsia-100 border-fuchsia-400 text-fuchsia-900",
  "transition metal": "bg-yellow-100 border-yellow-400 text-yellow-900",
  "post-transition metal": "bg-lime-100 border-lime-400 text-lime-900",
  "metalloid": "bg-emerald-100 border-emerald-400 text-emerald-900",
  "diatomic nonmetal": "bg-cyan-100 border-cyan-400 text-cyan-900",
  "polyatomic nonmetal": "bg-teal-100 border-teal-400 text-teal-900",
  "noble gas": "bg-violet-100 border-violet-400 text-violet-900",
  "unknown": "bg-gray-100 border-gray-400 text-gray-900"
};

export const getStateAtTemperature = (element: Element, tempK: number): 'solid' | 'liquid' | 'gas' | 'unknown' => {
  if (element.melt === undefined || element.boil === undefined) return 'unknown';
  if (tempK < element.melt) return 'solid';
  if (tempK < element.boil) return 'liquid';
  return 'gas';
};

export const getIonChargeColor = (charge: string): string => {
  if (charge.startsWith('+')) return 'text-red-600 bg-red-50';
  if (charge.startsWith('-')) return 'text-blue-600 bg-blue-50';
  return 'text-gray-600 bg-gray-50';
};
